version: '3.6'

services:
  web:
    image: dc
    ports:
      - 3002:3000
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=abcd1234
      - RAILS_SERVE_STATIC_FILES=true
      - API_SERVICE_BACKEND_URL_OPTIONS={"uk":"http://host.docker.internal:3000/","xi":"http://host.docker.internal:3000/"}
      - DUTY_CALCULATOR_HOST=http://localhost:3000
      - TRADE_TARIFF_FRONTEND_URL=http://localhost:3000
      - ROW_TO_NI=true
      - ROUTE_THROUGH_FRONTEND=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
