version: '3.6'

services:
  web:
    image: dc
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=abcd1234
      - RAILS_SERVE_STATIC_FILES=true
      - API_SERVICE_BACKEND_URL_OPTIONS={"uk":"https://dev.trade-tariff.service.gov.uk/","xi":"https://dev.trade-tariff.service.gov.uk/"}
      - DUTY_CALCULATOR_HOST="http://localhost:3000"
      - TRADE_TARIFF_FRONTEND_URL="http://localhost:3000"
      - ROW_TO_NI=true




