version: '3.6'

services:
  web:
    build: .
    ports:
      - 3002:3000
    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=abcd1234
      - RAILS_SERVE_STATIC_FILES=true
      - API_SERVICE_BACKEND_URL_OPTIONS={"uk":"https://tariff-frontend-dev.london.cloudapps.digital","xi":"https://tariff-frontend-dev.london.cloudapps.digital/xi"}
      - DUTY_CALCULATOR_HOST=http://localhost:3000
      - TRADE_TARIFF_FRONTEND_URL=http://localhost:3000
      - ROW_TO_NI=true
      - ROUTE_THROUGH_FRONTEND=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
